ALPHABET = "abcdefghijklmnopqrstuvwxyz"
OK_CHARS = ALPHABET + ALPHABET.upper() + "0123456789 "
OK_ALPHA_CHARS = ALPHABET + ALPHABET.upper() + " "

OUT_CHARS = ALPHABET + " "
# SNIPPETS_PER_FILE = 1024 * 1024
SNIPPETS_PER_FILE = 1024 * 128
EMPTY_CHAR = "~"
